name: EC2 Scheduler Stable

on:
  push:
    branches: [ main ]   # cron activate hone me help karega
  schedule:
    - cron: '*/5 * * * *'   # testing ke liye (har 5 min)
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  INSTANCE_IDS: i-066da3db8d10f1f49
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Schedule: ${{ github.event.schedule }}"
          date

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get Instance State
        run: |
          STATE=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_IDS \
            --query "Reservations[0].Instances[0].State.Name" \
            --output text)

          echo "Current state: $STATE"
          echo "STATE=$STATE" >> $GITHUB_ENV

      - name: Decide Action (Toggle)
        run: |
          if [[ "$STATE" == "running" ]]; then
            echo "ACTION=stop" >> $GITHUB_ENV
          else
            echo "ACTION=start" >> $GITHUB_ENV
          fi

      - name: Execute Action
        run: |
          echo "Final Action: $ACTION"

          if [[ "$ACTION" == "start" ]]; then
            aws ec2 start-instances --instance-ids $INSTANCE_IDS
          else
            aws ec2 stop-instances --instance-ids $INSTANCE_IDS
          fi
